<?php

namespace Database\Seeders;

use App\Models\PortfolioItem;
use App\Models\Product;
use App\Models\ProductVariant;
use App\Models\SiteSetting;
use App\Models\TattooStyle;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;

class RealArtworksSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Update Artist & Studio Settings with real data
        SiteSetting::set('artist_name', 'Wladimir Inostroza ("Fredo")');
        SiteSetting::set('artist_bio_es', 'Wladimir Inostroza ("Fredo" / "Fredosis") es un dibujante, pintor y artista del tatuaje chileno internacionalmente reconocido por sus dibujos anamórficos en 3D a grafito y sus obras pictóricas surrealistas. Su talento ha sido reseñado en The Sun, Daily Mail, el libro oficial de Ripley\'s Believe It or Not! (pág. 221) y el documental sobre Tool "The Holy Gift". Actualmente tatúa y produce arte original en su estudio privado en Santiago de Chile.');
        SiteSetting::set('artist_bio_en', 'Wladimir Inostroza ("Fredo" / "Fredosis") is an acclaimed Chilean draftsman, painter and tattoo artist recognized worldwide for his mind-bending 3D anamorphic pencil drawings and surrealist oil paintings. Featured in The Sun, Daily Mail, Ripley\'s Believe It or Not! (page 221), and the Tool documentary "The Holy Gift". Currently tattooing and producing fine art from his private studio in Santiago, Chile.');
        SiteSetting::set('contact_email', 'fredocontacto@gmail.com');
        SiteSetting::set('paypal_account', 'fredocontacto@gmail.com');
        SiteSetting::set('instagram_handle', '@fredosis.art');

        // 2. Clear placeholder or old records to ensure clean real archive
        Schema::disableForeignKeyConstraints();
        PortfolioItem::truncate();
        ProductVariant::truncate();
        Product::truncate();
        Schema::enableForeignKeyConstraints();

        $surrealStyle = TattooStyle::where('slug', 'surrealism')->first()?->id ?? 1;
        $blackworkStyle = TattooStyle::where('slug', 'blackwork')->first()?->id ?? 1;

        // 3. SEED REAL GALLERY (Drawings listo - 45 high quality artworks)
        $galleryItems = [
            [
                'file' => 'anamorfosis-hd.jpg',
                'title' => 'Anamorfosis 3D',
                'category' => 'drawings',
                'medium' => 'Grafito y técnica mixta sobre madera',
                'dimensions' => '40 x 30 cm',
                'year' => '2009',
                'is_featured' => true,
                'description' => 'Pieza pionera en el desarrollo del dibujo anamórfico en tres dimensiones sobre madera.',
            ],
            [
                'file' => 'curiosity.jpg',
                'title' => 'Curiosity',
                'category' => 'drawings',
                'medium' => 'Grafito anamórfico sobre papel',
                'dimensions' => '53 x 37 cm',
                'year' => '2009',
                'is_featured' => true,
                'description' => 'La emblemática obra de anamorfosis en 3D que se viralizó globalmente en The Sun y Daily Mail.',
            ],
            [
                'file' => 'dualism.jpg',
                'title' => 'Dualism',
                'category' => 'drawings',
                'medium' => 'Grafito sobre papel',
                'dimensions' => '53 x 37 cm',
                'year' => '2011',
                'is_featured' => true,
                'description' => 'Estudio de volumen ilusorio y dualidad psíquica a través de tramas de grafito degradado.',
            ],
            [
                'file' => 'sentao-de-pana-final-hd.jpg',
                'title' => 'Sentao de Pana',
                'category' => 'drawings',
                'medium' => 'Grafito de alta graduación sobre papel',
                'dimensions' => '53 x 37 cm',
                'year' => '2020',
                'is_featured' => true,
                'description' => 'Figura anatómica monumental en grafito con sombreados envolventes y tensión dramática.',
            ],
            [
                'file' => 'cabeza-hacia-atras-dibujo-impresion-mas-claro.jpg',
                'title' => 'Cabeza Hacia Atrás',
                'category' => 'drawings',
                'medium' => 'Grafito tonal sobre papel Fabriano',
                'dimensions' => '42 x 29 cm',
                'year' => '2020',
                'is_featured' => true,
                'description' => 'Torsión anatómica del cuello y cráneo en claroscuro de alto contraste.',
            ],
            [
                'file' => 'caremanos-hd.jpg',
                'title' => 'Caremanos',
                'category' => 'drawings',
                'medium' => 'Grafito y técnica mixta',
                'dimensions' => '42 x 29 cm',
                'year' => '2020',
                'is_featured' => true,
                'description' => 'Metamorfosis surrealista donde los rasgos faciales son formados por dedos entrelazados.',
            ],
            [
                'file' => 'fecundacion-de-una-idea.jpg',
                'title' => 'Fecundación de una Idea',
                'category' => 'drawings',
                'medium' => 'Grafito sobre papel',
                'dimensions' => '42 x 29 cm',
                'year' => '2020',
                'is_featured' => true,
                'description' => 'Alegoría poética del nacimiento del pensamiento y el proceso creador.',
            ],
            [
                'file' => 'floating-hd.jpg',
                'title' => 'Floating (Entrega)',
                'category' => 'drawings',
                'medium' => 'Grafito sobre papel',
                'dimensions' => '42 x 29 cm',
                'year' => '2021',
                'is_featured' => true,
                'description' => 'Cuerpo en ingravidez disuelto en aguas celestiales y nubes densas.',
            ],
            [
                'file' => 'polillas-scaneado.jpg',
                'title' => 'Polillas',
                'category' => 'drawings',
                'medium' => 'Grafito sobre papel',
                'dimensions' => '42 x 29 cm',
                'year' => '2020',
                'is_featured' => true,
                'description' => 'Busto femenino abriéndose en un mecanismo de reloj del cual emergen polillas de luz.',
            ],
            [
                'file' => 'dmt-hd.jpg',
                'title' => 'DMT',
                'category' => 'paintings',
                'medium' => 'Óleo sobre lienzo',
                'dimensions' => '100 x 70 cm',
                'year' => '2021',
                'is_featured' => true,
                'description' => 'Pintura al óleo sobre estados alterados de la conciencia y geometría transdimensional.',
            ],
            [
                'file' => 'espejo-oceano-hd.jpg',
                'title' => 'Mirror (Espejo Océano)',
                'category' => 'paintings',
                'medium' => 'Pastel suave (Soft pastel) sobre papel',
                'dimensions' => '65 x 50 cm',
                'year' => '2022',
                'is_featured' => true,
                'description' => 'Sacerdote que sostiene un cáliz reflectante del cosmos, con cráneos bifurcados en pastel suave.',
            ],
            [
                'file' => 'oleo-fuego.jpg',
                'title' => 'El Creador',
                'category' => 'paintings',
                'medium' => 'Óleo sobre lienzo',
                'dimensions' => '150 x 170 cm',
                'year' => '2024',
                'is_featured' => true,
                'description' => 'Gran formato al óleo: un navegante que modela la llama viva sobre un islote en el océano nocturno.',
            ],
            [
                'file' => 'panoptico-oil-60-x-50-cms-2021.jpg',
                'title' => 'Panóptico',
                'category' => 'paintings',
                'medium' => 'Óleo sobre lienzo',
                'dimensions' => '60 x 50 cm',
                'year' => '2021',
                'is_featured' => true,
                'description' => 'Reflexión pictórica sobre la vigilancia interna, la culpa y la multiplicidad del yo.',
            ],
            [
                'file' => 'las_cuerdas_de_la_ignorancia_by_byfredo_d3dfy5z.jpg',
                'title' => 'Las Cuerdas de la Ignorancia',
                'category' => 'drawings',
                'medium' => 'Grafito sobre papel',
                'dimensions' => '53 x 37 cm',
                'year' => '2011',
                'is_featured' => true,
                'description' => 'Obra clásica de la etapa temprana de Fredo que explora el adoctrinamiento mental.',
            ],
            [
                'file' => 'les_idees_sont_eternelles_by_byfredo_d44mczl.jpg',
                'title' => 'Les Idées Sont Éternelles',
                'category' => 'drawings',
                'medium' => 'Grafito sobre papel',
                'dimensions' => '42 x 29 cm',
                'year' => '2011',
                'is_featured' => true,
                'description' => 'Composición conceptual sobre la inmortalidad de la mente y la creación.',
            ],
            [
                'file' => 'perception_by_fredoart-d50hoho.jpg',
                'title' => 'Perception (3D Anamorphic)',
                'category' => 'drawings',
                'medium' => 'Grafito sobre papel',
                'dimensions' => '53 x 37 cm',
                'year' => '2012',
                'is_featured' => true,
                'description' => 'Ilusión óptica anamórfica de mano emergiendo del plano bidimensional.',
            ],
            [
                'file' => 'the-kiss.jpg',
                'title' => 'The Kiss',
                'category' => 'drawings',
                'medium' => 'Grafito sobre papel',
                'dimensions' => '30 x 20 cm',
                'year' => '2011',
                'is_featured' => true,
                'description' => 'Beso ilusorio en 3D que trasciende la superficie del bloc de dibujo.',
            ],
            [
                'file' => 'the_kiss_ii_by_byfredo_d7jw4t0.jpg',
                'title' => 'The Kiss II',
                'category' => 'drawings',
                'medium' => 'Grafito sobre papel',
                'dimensions' => '42 x 29 cm',
                'year' => '2014',
                'is_featured' => false,
                'description' => 'Segunda entrega de la serie The Kiss con mayor profundidad anatómica.',
            ],
            [
                'file' => 'the_roof_by_byfredo_d2zoqll.jpg',
                'title' => 'The Roof',
                'category' => 'drawings',
                'medium' => 'Grafito sobre papel',
                'dimensions' => '42 x 29 cm',
                'year' => '2012',
                'is_featured' => false,
                'description' => 'Interacción anamórfica con la arquitectura circundante.',
            ],
            [
                'file' => 'punto_de_vista_by_byfredo_d1150gq.jpg',
                'title' => 'Punto de Vista',
                'category' => 'drawings',
                'medium' => 'Grafito sobre papel',
                'dimensions' => '42 x 29 cm',
                'year' => '2010',
                'is_featured' => false,
                'description' => 'Estudio de perspectiva forzada en hoja abierta.',
            ],
            [
                'file' => 'carehongo.jpg',
                'title' => 'Carehongo',
                'category' => 'drawings',
                'medium' => 'Grafito sobre papel',
                'dimensions' => '42 x 29 cm',
                'year' => '2021',
                'is_featured' => false,
                'description' => 'Hibridación micorriza y rostro humano.',
            ],
            [
                'file' => 'cara-separada-hd.jpg',
                'title' => 'Cara Separada (New)',
                'category' => 'drawings',
                'medium' => 'Grafito y técnica mixta',
                'dimensions' => '21 x 29 cm',
                'year' => '2022',
                'is_featured' => false,
                'description' => 'Deconstrucción facial y fragmentación de la identidad.',
            ],
            [
                'file' => 'cuarentena-depre.jpg',
                'title' => 'Quarantine',
                'category' => 'drawings',
                'medium' => 'Grafito sobre papel',
                'dimensions' => '42 x 29 cm',
                'year' => '2021',
                'is_featured' => false,
                'description' => 'Testimonio gráfico del encierro, la soledad y la introspección forzada.',
            ],
            [
                'file' => 'exposicion.jpg',
                'title' => 'Exposición',
                'category' => 'drawings',
                'medium' => 'Tinta y grafito sobre papel',
                'dimensions' => '21 x 29 cm',
                'year' => '2022',
                'is_featured' => false,
                'description' => 'Trilogía de figuras que contemplan la luminosidad visceral de un corazón expuesto.',
            ],
            [
                'file' => 'healing.jpg',
                'title' => 'Healing',
                'category' => 'drawings',
                'medium' => 'Tinta, grafito y técnica mixta',
                'dimensions' => '21 x 29 cm',
                'year' => '2022',
                'is_featured' => false,
                'description' => 'Sanación en el bosque oscuro: el cuerpo abierto a la regeneración natural.',
            ],
            [
                'file' => 'guitarrista-menos-contraste.jpg',
                'title' => 'Guitarrista',
                'category' => 'drawings',
                'medium' => 'Grafito sobre papel',
                'dimensions' => '42 x 29 cm',
                'year' => '2021',
                'is_featured' => false,
                'description' => 'Fusión del músico con su instrumento acústico en un único organismo sonoro.',
            ],
            [
                'file' => 'insurrecion-hd.jpg',
                'title' => 'Insurrección',
                'category' => 'drawings',
                'medium' => 'Grafito sobre papel',
                'dimensions' => '42 x 29 cm',
                'year' => '2019',
                'is_featured' => false,
                'description' => 'Multitud insurgente y catarsis social en las calles de Santiago.',
            ],
            [
                'file' => 'mujer-en-arbol.jpg',
                'title' => 'Into The Tree (Resiliencia)',
                'category' => 'drawings',
                'medium' => 'Grafito sobre papel',
                'dimensions' => '42 x 29 cm',
                'year' => '2022',
                'is_featured' => false,
                'description' => 'Figura solitaria refugiada en la oquedad luminosa de un roble milenario.',
            ],
            [
                'file' => 'mujer-sin-cabeza-png.jpg',
                'title' => 'Self',
                'category' => 'drawings',
                'medium' => 'Tinta y grafito sobre papel',
                'dimensions' => '21 x 29 cm',
                'year' => '2022',
                'is_featured' => false,
                'description' => 'Figura femenina entronizada en un vórtice marino con un vacío en el rostro.',
            ],
            [
                'file' => 'oil-palida.jpg',
                'title' => 'Bad Trip',
                'category' => 'paintings',
                'medium' => 'Óleo sobre madera',
                'dimensions' => '20 x 15 cm',
                'year' => '2021',
                'is_featured' => false,
                'description' => 'Pequeño formato al óleo de atmósfera claustrofóbica y nocturna.',
            ],
            [
                'file' => 'oleo-mujeres.jpg',
                'title' => 'Terapia, Amistad y Muerte',
                'category' => 'paintings',
                'medium' => 'Óleo sobre lienzo',
                'dimensions' => '40 x 50 cm',
                'year' => '2024',
                'is_featured' => false,
                'description' => 'Composición íntima al óleo con luces crepusculares de velatorio.',
            ],
            [
                'file' => 'palida-hd.jpg',
                'title' => 'Anxiety',
                'category' => 'drawings',
                'medium' => 'Grafito sobre papel',
                'dimensions' => '27 x 37 cm',
                'year' => '2015',
                'is_featured' => false,
                'description' => 'Estudio somático sobre la ansiedad y la parálisis sensorial.',
            ],
            [
                'file' => 'paralisis.jpg',
                'title' => 'Parálisis de Sueño',
                'category' => 'paintings',
                'medium' => 'Óleo sobre lienzo',
                'dimensions' => '65 x 40 cm',
                'year' => '2018',
                'is_featured' => false,
                'description' => 'Monstruosidad onírica y sombras hipnagógicas al óleo.',
            ],
            [
                'file' => 'self-2-oil-40-x-50-cms-2021.jpg',
                'title' => 'Self 2',
                'category' => 'paintings',
                'medium' => 'Óleo sobre lienzo',
                'dimensions' => '40 x 50 cm',
                'year' => '2021',
                'is_featured' => false,
                'description' => 'Autorretrato deconstruido en veladuras al óleo.',
            ],
            [
                'file' => 'submission_by_byfredo_d3iik4k.jpg',
                'title' => 'Submission',
                'category' => 'drawings',
                'medium' => 'Grafito sobre papel',
                'dimensions' => '42 x 29 cm',
                'year' => '2011',
                'is_featured' => false,
                'description' => 'Pieza anamórfica donde el dibujo parece tomar posesión de la mano creadora.',
            ],
            [
                'file' => 'tinta-acuarela.jpg',
                'title' => 'Trip',
                'category' => 'paintings',
                'medium' => 'Acuarela y tinta sobre papel',
                'dimensions' => '30 x 20 cm',
                'year' => '2020',
                'is_featured' => false,
                'description' => 'Exploración fluida de pigmentos al agua y trazos caligráficos.',
            ],
            [
                'file' => 'blue_by_byfredo_daa1bib.jpg',
                'title' => 'Blue',
                'category' => 'drawings',
                'medium' => 'Grafito sobre papel',
                'dimensions' => '42 x 29 cm',
                'year' => '2015',
                'is_featured' => false,
                'description' => 'Melancolía y tonalidades frías mediante grafito pulido.',
            ],
            [
                'file' => 'emotional_dependence_by_byfredo_d2p0z5e.jpg',
                'title' => 'Emotional Dependence',
                'category' => 'drawings',
                'medium' => 'Grafito sobre papel',
                'dimensions' => '42 x 29 cm',
                'year' => '2010',
                'is_featured' => false,
                'description' => 'Cuerpos entrelazados como una única masa indivisible.',
            ],
            [
                'file' => 'femmes_by_byfredo_d1va348.jpg',
                'title' => 'Femmes',
                'category' => 'drawings',
                'medium' => 'Grafito sobre papel',
                'dimensions' => '42 x 29 cm',
                'year' => '2010',
                'is_featured' => false,
                'description' => 'Boceto rápido de figura en perspectiva distorsionada.',
            ],
            [
                'file' => 'dibujohd.jpg',
                'title' => 'Sufragio',
                'category' => 'drawings',
                'medium' => 'Grafito sobre papel',
                'dimensions' => '53 x 37 cm',
                'year' => '2013',
                'is_featured' => false,
                'description' => 'Alegoría crítica de la masa humana y el poder institucional.',
            ],
            [
                'file' => 'img_5597.jpg',
                'title' => 'Escape',
                'category' => 'paintings',
                'medium' => 'Óleo sobre lienzo',
                'dimensions' => '50 x 70 cm',
                'year' => '2021',
                'is_featured' => false,
                'description' => 'Huida hacia los límites del marco pictórico.',
            ],
            [
                'file' => '1.jpg',
                'title' => 'Comunicación (Feeding)',
                'category' => 'paintings',
                'medium' => 'Óleo sobre madera',
                'dimensions' => '40 x 40 cm',
                'year' => '2020',
                'is_featured' => false,
                'description' => 'Dos figuras conectadas por flujos de materia luminosa.',
            ],
            [
                'file' => '2.jpg',
                'title' => 'Monstruo',
                'category' => 'drawings',
                'medium' => 'Grafito sobre papel',
                'dimensions' => '21 x 29 cm',
                'year' => '2016',
                'is_featured' => false,
                'description' => 'Estudio miológico y anatómico de espalda en tensión extrema.',
            ],
            [
                'file' => '3.jpg',
                'title' => 'Los Hedonistas (Esculturas)',
                'category' => 'drawings',
                'medium' => 'Grafito sobre papel',
                'dimensions' => '29 x 42 cm',
                'year' => '2023',
                'is_featured' => false,
                'description' => 'Ritual colectivo de banquetes mórbidos y placer sensual.',
            ],
            [
                'file' => '5.jpg',
                'title' => 'Untitled (Perfil al Óleo)',
                'category' => 'paintings',
                'medium' => 'Óleo sobre lienzo',
                'dimensions' => '40 x 30 cm',
                'year' => '2017',
                'is_featured' => false,
                'description' => 'Retrato femenino en penumbra con veladuras oscuras.',
            ],
        ];

        $sort = 1;
        foreach ($galleryItems as $item) {
            PortfolioItem::create([
                'title' => $item['title'],
                'slug' => Str::slug($item['title'].'-'.$item['year']),
                'category' => $item['category'],
                'medium' => $item['medium'],
                'dimensions' => $item['dimensions'],
                'year' => $item['year'],
                'image_url' => '/images/gallery/'.$item['file'],
                'description' => $item['description'],
                'style_id' => $item['category'] === 'paintings' ? $surrealStyle : $blackworkStyle,
                'is_featured' => $item['is_featured'],
                'sort_order' => $sort++,
            ]);
        }

        // 4. SEED REAL SHOP PRODUCTS (Original Drawings for Sale / Productos - 24 items with real prices)
        $shopProducts = [
            [
                'file' => 'mirror-soft-pastel-65-x-50-cms-2022.jpg',
                'title' => 'Mirror',
                'technique' => 'Soft pastel sobre papel',
                'dimensions' => '50 x 60 cms',
                'year' => '2022',
                'price_usd' => 400.00,
                'is_featured' => true,
                'description' => 'Obra original destacada en pastel suave. Sacerdote cósmico que sostiene el cáliz reflectante. Dibujo original único firmado por el autor.',
            ],
            [
                'file' => 'anamorfosis-mix-media-on-wood-2009.jpg',
                'title' => 'Anamorfosis',
                'technique' => 'Mixed media on wood',
                'dimensions' => '40 x 30 cms',
                'year' => '2009',
                'price_usd' => 200.00,
                'is_featured' => true,
                'description' => 'Pieza histórica original en madera. Técnica mixta sobre tabla del período pionero de anamorfosis 3D.',
            ],
            [
                'file' => 'curiosity-grafito-53-x-37-cms-2009.jpg',
                'title' => 'Curiosity',
                'technique' => 'Grafito anamórfico sobre papel',
                'dimensions' => '53 x 37 cms',
                'year' => '2009',
                'price_usd' => 300.00,
                'is_featured' => true,
                'description' => 'Una de las obras más reconocidas a nivel mundial de Fredo, publicada en The Sun y Daily Mail.',
            ],
            [
                'file' => 'dmt-100-x-70-oil-2021.jpg',
                'title' => 'DMT',
                'technique' => 'Óleo sobre lienzo',
                'dimensions' => '100 x 70 cms',
                'year' => '2021',
                'price_usd' => 350.00,
                'is_featured' => true,
                'description' => 'Lienzo original al óleo de gran formato. Geometría visionaria y tonalidades cósmicas.',
            ],
            [
                'file' => 'polillas-grafito-42-x-29-cms-2020.jpg',
                'title' => 'Polillas',
                'technique' => 'Grafito sobre papel',
                'dimensions' => '42 x 29 cms',
                'year' => '2020',
                'price_usd' => 200.00,
                'is_featured' => true,
                'description' => 'Dibujo original a lápiz grafito con delicados contrastes de luz y mecanismo anatómico.',
            ],
            [
                'file' => 'esculturas-grafito-42-x-29-cms-2022.jpg',
                'title' => 'Los Hedonistas (Esculturas)',
                'technique' => 'Grafito sobre papel',
                'dimensions' => '42 x 29 cms',
                'year' => '2022',
                'price_usd' => 200.00,
                'is_featured' => true,
                'description' => 'Pieza original a grafito con micro-detalles en la piel de las figuras esculpidas.',
            ],
            [
                'file' => 'sufragio-grafito-53-x-37-cms-2013.jpg',
                'title' => 'Sufragio',
                'technique' => 'Grafito sobre papel',
                'dimensions' => '53 x 37 cms',
                'year' => '2013',
                'price_usd' => 250.00,
                'is_featured' => true,
                'description' => 'Obra original de crítica social y dimensión alegórica en gran formato de grafito.',
            ],
            [
                'file' => 'floating-grafito-42-x-29-cms-2021.jpg',
                'title' => 'Floating (Entrega)',
                'technique' => 'Grafito sobre papel',
                'dimensions' => '42 x 29 cms',
                'year' => '2021',
                'price_usd' => 180.00,
                'is_featured' => false,
                'description' => 'Original sobre papel. Atmósfera envolvente de nubes y cuerpos ingrávidos.',
            ],
            [
                'file' => 'into-the-tree-grafito-42-x-29-cms-2022.jpg',
                'title' => 'Into The Tree (Resiliencia)',
                'technique' => 'Grafito sobre papel',
                'dimensions' => '42 x 29 cms',
                'year' => '2022',
                'price_usd' => 150.00,
                'is_featured' => false,
                'description' => 'Original a grafito. Refugio íntimo de la conciencia en el tronco viviente.',
            ],
            [
                'file' => 'exposicion-grafito-mix-media-21-x-29-cms-2022.jpg',
                'title' => 'Exposición',
                'technique' => 'Tinta y grafito sobre papel',
                'dimensions' => '21 x 29 cms',
                'year' => '2022',
                'price_usd' => 200.00,
                'is_featured' => false,
                'description' => 'Pieza original en tinta china y grafito con luz interna radiante.',
            ],
            [
                'file' => 'healing-ink-mix-media-21-x-29-cms-2022.jpg',
                'title' => 'Healing',
                'technique' => 'Tinta y técnica mixta',
                'dimensions' => '21 x 29 cms',
                'year' => '2022',
                'price_usd' => 200.00,
                'is_featured' => false,
                'description' => 'Composición original en tinta y técnicas mixtas sobre papel de algodón.',
            ],
            [
                'file' => 'self-grafito-mix-media-21-x-29-cms-2022.jpg',
                'title' => 'Self',
                'technique' => 'Grafito y técnica mixta',
                'dimensions' => '21 x 29 cms',
                'year' => '2022',
                'price_usd' => 200.00,
                'is_featured' => false,
                'description' => 'Exploración del sí mismo y el vacío interior mediante trazos finos.',
            ],
            [
                'file' => 'new-grafito-mix-media-21-x-29-cms-2022.jpg',
                'title' => 'Nuevo',
                'technique' => 'Tinta y técnica mixta',
                'dimensions' => '21 x 29 cms',
                'year' => '2022',
                'price_usd' => 200.00,
                'is_featured' => false,
                'description' => 'Original en tinta con paisaje lunar y cabezas entrelazadas.',
            ],
            [
                'file' => 'feeding-oil-40-x-40-cms-2020.jpg',
                'title' => 'Feeding (Comunicación)',
                'technique' => 'Óleo sobre madera',
                'dimensions' => '40 x 40 cms',
                'year' => '2020',
                'price_usd' => 180.00,
                'is_featured' => false,
                'description' => 'Tabla al óleo original con tonalidades cálidas de ocre y naranja.',
            ],
            [
                'file' => 'panoptico-oil-60-x-50-cms-2021.jpg',
                'title' => 'Panóptico',
                'technique' => 'Óleo sobre lienzo',
                'dimensions' => '60 x 50 cms',
                'year' => '2021',
                'price_usd' => 280.00,
                'is_featured' => false,
                'description' => 'Original al óleo sobre tela. Multiplicidad visual y claroscuro.',
            ],
            [
                'file' => 'paralisis-de-sueno-oil-65-x-40-cms-2018.jpg',
                'title' => 'Parálisis de Sueño',
                'technique' => 'Óleo sobre lienzo',
                'dimensions' => '65 x 40 cms',
                'year' => '2018',
                'price_usd' => 300.00,
                'is_featured' => false,
                'description' => 'Pintura original al óleo inspirada en el fenómeno de la catalepsia nocturna.',
            ],
            [
                'file' => 'escape-oil-50-x-70-cms-2021.jpg',
                'title' => 'Escape',
                'technique' => 'Óleo sobre lienzo',
                'dimensions' => '50 x 70 cms',
                'year' => '2021',
                'price_usd' => 320.00,
                'is_featured' => false,
                'description' => 'Lienzo original al óleo con contrastes profundos y escape formal.',
            ],
            [
                'file' => 'inside-40-x-30-oil-2018.jpg',
                'title' => 'Inside',
                'technique' => 'Óleo sobre lienzo',
                'dimensions' => '40 x 30 cms',
                'year' => '2018',
                'price_usd' => 220.00,
                'is_featured' => false,
                'description' => 'Pintura al óleo original de gabinete interior y silueta humana.',
            ],
            [
                'file' => 'las-cuerdas-grafito-53-x-37-cms-2011.jpg',
                'title' => 'Las Cuerdas',
                'technique' => 'Grafito sobre papel',
                'dimensions' => '53 x 37 cms',
                'year' => '2011',
                'price_usd' => 280.00,
                'is_featured' => false,
                'description' => 'Dibujo original a grafito clásico del portafolio histórico de Fredo.',
            ],
            [
                'file' => 'quarantine-grafito-42-x-29-cms-2021.jpg',
                'title' => 'Quarantine',
                'technique' => 'Grafito sobre papel',
                'dimensions' => '42 x 29 cms',
                'year' => '2021',
                'price_usd' => 200.00,
                'is_featured' => false,
                'description' => 'Obra original a grafito testimonio del período de cuarentena.',
            ],
            [
                'file' => 'anxiety-grafito-27-x-37-cms-2015.jpg',
                'title' => 'Anxiety',
                'technique' => 'Grafito sobre papel',
                'dimensions' => '27 x 37 cms',
                'year' => '2015',
                'price_usd' => 180.00,
                'is_featured' => false,
                'description' => 'Dibujo original sobre papel con texturas intensas de tensión muscular.',
            ],
            [
                'file' => 'bad-trip-oil-20-x-15-cms-2021.jpg',
                'title' => 'Bad Trip',
                'technique' => 'Óleo sobre madera',
                'dimensions' => '20 x 15 cms',
                'year' => '2021',
                'price_usd' => 140.00,
                'is_featured' => false,
                'description' => 'Pequeño formato al óleo original, pieza coleccionable.',
            ],
            [
                'file' => 'self-2-oil-40-x-50-cms-2021.jpg',
                'title' => 'Self 2',
                'technique' => 'Óleo sobre lienzo',
                'dimensions' => '40 x 50 cms',
                'year' => '2021',
                'price_usd' => 260.00,
                'is_featured' => false,
                'description' => 'Retrato al óleo sobre tela con técnica directa y veladuras.',
            ],
            [
                'file' => 'trip-watercolor-30-x-20-cms-2020.jpg',
                'title' => 'Trip',
                'technique' => 'Acuarela y tinta sobre papel',
                'dimensions' => '30 x 20 cms',
                'year' => '2020',
                'price_usd' => 160.00,
                'is_featured' => false,
                'description' => 'Obra original en acuarela sobre papel texturado de 300g.',
            ],
        ];

        foreach ($shopProducts as $prod) {
            $priceUsd = (float) $prod['price_usd'];
            $priceClp = round($priceUsd * 950);
            $slug = Str::slug($prod['title'].'-'.$prod['year']);

            $product = Product::create([
                'title' => $prod['title'],
                'slug' => $slug,
                'description' => $prod['description'].' Envíos protegidos a todo el mundo por Correos de Chile en tubo o caja rígida de alta resistencia. Para compradores en Chile, transferencia bancaria directa disponible.',
                'short_description' => $prod['technique'].' — '.$prod['dimensions'].' ('.$prod['year'].') — © FREDO',
                'technique' => $prod['technique'],
                'dimensions' => $prod['dimensions'],
                'category' => str_contains(strtolower($prod['technique']), 'óleo') || str_contains(strtolower($prod['technique']), 'oil') ? 'pinturas' : 'dibujos',
                'main_image' => '/images/shop/'.$prod['file'],
                'gallery_images' => [
                    '/images/shop/'.$prod['file'],
                ],
                'base_price_usd' => $priceUsd,
                'base_price_clp' => $priceClp,
                'has_original' => true,
                'original_sold' => false,
                'is_featured' => $prod['is_featured'],
                'is_active' => true,
            ]);

            // Create Original Drawing variant matching sketch
            ProductVariant::create([
                'product_id' => $product->id,
                'format_name' => 'Dibujo Original Único ('.$prod['dimensions'].')',
                'format_type' => 'ORIGINAL',
                'price_usd' => $priceUsd,
                'price_clp' => $priceClp,
                'price_eur' => round($priceUsd * 0.92, 2),
                'price_mxn' => round($priceUsd * 19.8, 2),
                'stock' => 1,
                'is_available' => true,
            ]);

            // Create Fine Art Print variant
            ProductVariant::create([
                'product_id' => $product->id,
                'format_name' => 'Lámina Fine Art Giclée (Algodón Hahnemühle)',
                'format_type' => 'PRINT',
                'price_usd' => 45.00,
                'price_clp' => 42000.00,
                'price_eur' => 41.00,
                'price_mxn' => 890.00,
                'stock' => 25,
                'is_available' => true,
            ]);
        }
    }
}
